---
- name: shut down all azure hosts
  hosts: all
  connection: local

  tasks: 
- name: Get facts for all virtual machines of a resource group
  azure_rm_virtualmachine_info:
  resource_group: "{{ resourcegroup_name }}"

...
