---
- name: shut down all azure hosts
  hosts: all
  connection: local

  tasks: 
  - name: calling shutdown
    azure_rm_virtualmachine: 
      name: Hostname
      resource_group: "{{ resourcegroup_name }}"
      started: no
